using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using System.Collections.Concurrent;
using System.Threading;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TeamsBot.Meetings;

namespace TeamsBot.Bot;

/// <summary>
/// Calls the Microsoft Graph Communications REST API to join and leave Teams meetings.
///
/// Token refresh: Graph tokens expire after ~3599 seconds. This service caches the
/// token and refreshes it 5 minutes before expiry so long meetings never break.
/// </summary>
public sealed class GraphCallsService
{
    private const string GraphBase = "https://graph.microsoft.com/v1.0";
    private const string TokenEndpoint =
        "https://login.microsoftonline.com/{0}/oauth2/v2.0/token";

    private readonly IConfiguration _config;
    private readonly MeetingStore _store;
    private readonly ILogger<GraphCallsService> _logger;
    private readonly HttpClient _http;

    // ── per-tenant token cache ─────────────────────────────────────────────
    private readonly ConcurrentDictionary<string, (string Token, DateTimeOffset Expiry)> _tokenCache = new();
    private readonly SemaphoreSlim _tokenLock = new(1, 1);

    // ── active calls ─────────────────────────────────────────────────────────
    private readonly ConcurrentDictionary<string, string> _callToMeeting = new(); // callId → meetingId

    public GraphCallsService(
        IConfiguration config,
        MeetingStore store,
        ILogger<GraphCallsService> logger,
        IHttpClientFactory httpFactory)
    {
        _config = config;
        _store  = store;
        _logger = logger;
        _http   = httpFactory.CreateClient("Graph");
    }

    // ── public call ID lookup ─────────────────────────────────────────────────
    public string? GetMeetingId(string callId) =>
        _callToMeeting.TryGetValue(callId, out var m) ? m : null;

    // ── join ─────────────────────────────────────────────────────────────────

    /// <summary>
    /// Join a Teams meeting via POST /communications/calls.
    /// Returns the Graph call ID on success.
    /// </summary>
    public async Task<string> JoinMeetingAsync(
        string joinUrl,
        string meetingId,
        string mediaBlob,          // base64 blob from MediaPlatformService
        string callbackUri,
        string? organizerTenant = null,
        CancellationToken ct = default)
    {
        // Priority: explicit organizer tenant → extracted from URL → configured meeting tenant → home tenant fallback
        var tenantId = organizerTenant
                       ?? ExtractTenantFromUrl(joinUrl)
                       ?? _config["MeetingTenantId"]
                       ?? _config["MicrosoftAppTenantId"]!;

        // Token must be acquired for the same tenant used in the call body
        var token = await GetAccessTokenAsync(tenantId, ct);
        var meetingInfo = BuildMeetingInfo(joinUrl);

        // Blob MUST be non-empty — MeetingsController must supply it.
        // Never fall back to serviceHostedMediaConfig: that delivers zero PCM audio to the bot.
        if (string.IsNullOrEmpty(mediaBlob))
            throw new InvalidOperationException(
                "MediaConfigBlob is null or empty. TeamsBot.Media service failed to create a session. " +
                "Check that TeamsBotMedia is running and port 8446 is reachable.");

        var body = new JsonObject
        {
            ["@odata.type"]       = "#microsoft.graph.call",
            ["callbackUri"]       = $"{callbackUri}/api/calls/callback",
            ["requestedModalities"] = new JsonArray("audio"),
            // appHostedMediaConfig: RMP SDK in TeamsBot.Media receives raw PCM audio.
            // The mediaBlob is generated by MediaPlatformService.CreateMediaSession() in
            // TeamsBot.Media and passed through from MeetingsController.
            ["mediaConfig"] = new JsonObject
            {
                ["@odata.type"] = "#microsoft.graph.appHostedMediaConfig",
                ["blob"] = mediaBlob,
            },
            ["meetingInfo"] = meetingInfo,
            ["tenantId"]    = tenantId,
            ["source"] = new JsonObject
            {
                ["@odata.type"] = "#microsoft.graph.participantInfo",
                ["identity"] = new JsonObject
                {
                    ["@odata.type"] = "#microsoft.graph.identitySet",
                    ["application"] = new JsonObject
                    {
                        ["@odata.type"] = "#microsoft.graph.identity",
                        ["id"]          = _config["MicrosoftAppId"],
                        ["displayName"] = "Meeting Agent",
                    }
                }
            }
        };

        _logger.LogInformation("Joining meeting {MeetingId} (tenant={Tenant}), mediaConfig=appHosted, blobLen={BlobLen}",
            meetingId, tenantId[..8] + "...",
            mediaBlob.Length);

        var req = new HttpRequestMessage(HttpMethod.Post, $"{GraphBase}/communications/calls")
        {
            Content = new StringContent(body.ToJsonString(), Encoding.UTF8, "application/json"),
            Headers = { Authorization = new AuthenticationHeaderValue("Bearer", token) }
        };

        var resp = await _http.SendAsync(req, ct);
        if (!resp.IsSuccessStatusCode)
        {
            var err = await resp.Content.ReadAsStringAsync(ct);
            _logger.LogError("Graph join failed: {Status} — {Error}", resp.StatusCode, err);
            throw new InvalidOperationException($"Graph join failed: {resp.StatusCode} — {err[..Math.Min(err.Length, 400)]}");
        }

        var json = await resp.Content.ReadAsStringAsync(ct);
        var callId = JsonDocument.Parse(json).RootElement.GetProperty("id").GetString()!;

        _callToMeeting[callId] = meetingId;
        _logger.LogInformation("Graph call created: callId={CallId}, meeting={MeetingId}", callId, meetingId);

        return callId;
    }

    // ── leave ─────────────────────────────────────────────────────────────────

    public async Task LeaveAsync(string callId, CancellationToken ct = default)
    {
        var token = await GetAccessTokenAsync(ct: ct);
        var req = new HttpRequestMessage(HttpMethod.Delete, $"{GraphBase}/communications/calls/{callId}")
        {
            Headers = { Authorization = new AuthenticationHeaderValue("Bearer", token) }
        };
        var resp = await _http.SendAsync(req, ct);
        _callToMeeting.TryRemove(callId, out _);

        _logger.LogInformation("Left call {CallId}: HTTP {Status}", callId, resp.StatusCode);
    }

    // ── callback handling ─────────────────────────────────────────────────────

    /// <summary>
    /// Process an incoming Graph notification payload.
    /// Updates meeting state when the call becomes established or terminates.
    /// </summary>
    public void HandleCallback(JsonElement body, Action<string, string> onStateChange)
    {
        // Graph sends either { value: [...] } or a single notification
        var notifications = body.TryGetProperty("value", out var arr)
            ? arr.EnumerateArray()
            : new[] { body }.AsEnumerable().Select(x => x);

        foreach (var notif in notifications)
        {
            var resourceUrl = notif.TryGetProperty("resourceUrl", out var ru) ? ru.GetString() ?? "" : "";
            if (!resourceUrl.Contains("/communications/calls/"))
                continue;

            var resource = notif.TryGetProperty("resourceData", out var rd) ? rd : default;
            if (resource.ValueKind == JsonValueKind.Undefined || resource.ValueKind != JsonValueKind.Object)
                continue;

            var callId = resource.TryGetProperty("id", out var id) ? id.GetString() ?? "" : "";
            var state  = resource.TryGetProperty("state", out var st) ? st.GetString() ?? "" : "";

            if (string.IsNullOrEmpty(callId)) continue;

            _logger.LogInformation("Graph callback: callId={CallId}, state={State}", callId, state);
            onStateChange(callId, state);
        }
    }

    // ── token — with expiry-aware refresh ─────────────────────────────────────

    /// <summary>
    /// Get a valid Graph access token.
    /// Token is cached and refreshed 5 minutes before expiry to handle meetings
    /// that last longer than the standard ~1-hour token lifetime.
    /// </summary>
    private async Task<string> GetAccessTokenAsync(string? tenantId = null, CancellationToken ct = default)
    {
        tenantId ??= _config["MicrosoftAppTenantId"]!;

        // Fast path — cached token still valid with 5-minute buffer
        if (_tokenCache.TryGetValue(tenantId, out var cached) &&
            DateTimeOffset.UtcNow < cached.Expiry.AddMinutes(-5))
            return cached.Token;

        await _tokenLock.WaitAsync(ct);
        try
        {
            // Double-check inside lock
            if (_tokenCache.TryGetValue(tenantId, out cached) &&
                DateTimeOffset.UtcNow < cached.Expiry.AddMinutes(-5))
                return cached.Token;

            var url = string.Format(TokenEndpoint, tenantId);

            var form = new Dictionary<string, string>
            {
                ["grant_type"]    = "client_credentials",
                ["client_id"]     = _config["MicrosoftAppId"]!,
                ["client_secret"] = _config["MicrosoftAppPassword"]!,
                ["scope"]         = "https://graph.microsoft.com/.default",
            };

            var resp = await _http.PostAsync(url, new FormUrlEncodedContent(form), ct);
            resp.EnsureSuccessStatusCode();

            var json    = await resp.Content.ReadAsStringAsync(ct);
            using var doc = JsonDocument.Parse(json);

            var token     = doc.RootElement.GetProperty("access_token").GetString()!;
            var expiresIn = doc.RootElement.GetProperty("expires_in").GetInt32();
            var expiry    = DateTimeOffset.UtcNow.AddSeconds(expiresIn);

            _tokenCache[tenantId] = (token, expiry);

            _logger.LogInformation(
                "Graph token acquired for tenant {Tenant}. Expires at {Expiry} UTC (+{Sec}s).",
                tenantId[..8] + "...", expiry.UtcDateTime, expiresIn);

            return token;
        }
        finally
        {
            _tokenLock.Release();
        }
    }

    // ── URL helpers ───────────────────────────────────────────────────────────

    private static readonly Regex _newMeetRe =
        new(@"teams\.microsoft\.com/meet/([^/?#&]+)", RegexOptions.IgnoreCase);

    private static JsonObject BuildMeetingInfo(string joinUrl)
    {
        // New short-link: teams.microsoft.com/meet/<joinId>?p=<passcode>
        var m = _newMeetRe.Match(joinUrl);
        if (m.Success)
        {
            var node = new JsonObject
            {
                ["@odata.type"] = "#microsoft.graph.joinMeetingIdMeetingInfo",
                ["joinMeetingId"] = m.Groups[1].Value,
            };
            var qs = System.Web.HttpUtility.ParseQueryString(new Uri(joinUrl).Query);
            if (qs["p"] is { } passcode)
                node["passcode"] = passcode;
            return node;
        }

        // Old-format /l/meetup-join/ — use tokenMeetingInfo
        return new JsonObject
        {
            ["@odata.type"] = "#microsoft.graph.tokenMeetingInfo",
            ["token"]       = joinUrl,
        };
    }

    private static string? ExtractTenantFromUrl(string joinUrl)
    {
        try
        {
            var qs  = System.Web.HttpUtility.ParseQueryString(new Uri(joinUrl).Query);
            var ctx = qs["context"];
            if (ctx is null) return null;
            var doc = JsonDocument.Parse(Uri.UnescapeDataString(ctx));
            return doc.RootElement.TryGetProperty("Tid", out var tid) ? tid.GetString() : null;
        }
        catch { return null; }
    }

    // ── transcript polling (Graph onlineMeetings transcripts API) ─────────────
    //
    // With serviceHostedMediaConfig the bot never receives raw audio, so we
    // cannot push PCM to Azure Speech. Instead we poll Teams' native transcript
    // (VTT) via Graph every 5 s. Requires the following app permissions in
    // the MEETING tenant (42f2ab09…):
    //   OnlineMeetings.Read.All
    //   OnlineMeetingTranscript.Read.All
    // If Teams transcription is not running the VTT will be empty — polling
    // degrades silently and retries until call terminates.

    private readonly ConcurrentDictionary<string, CancellationTokenSource> _pollers = new();

    public void StartTranscriptPolling(string callId, string meetingId)
    {
        var cts = new CancellationTokenSource();
        _pollers[callId] = cts;
        _ = PollTranscriptsLoopAsync(callId, meetingId, cts.Token);
    }

    public void StopTranscriptPolling(string callId)
    {
        if (_pollers.TryRemove(callId, out var cts))
            cts.Cancel();
    }

    private async Task PollTranscriptsLoopAsync(string callId, string meetingId, CancellationToken ct)
    {
        // Wait for the call to fully establish before first poll
        try { await Task.Delay(8_000, ct); } catch (OperationCanceledException) { return; }

        var meeting = _store.GetMeeting(meetingId);
        if (meeting is null) return;

        string? organizerId    = null;
        string? onlineMeetingId = null;
        // transcriptId → how many chars of VTT we have already parsed
        var vttOffset = new Dictionary<string, int>();

        _logger.LogInformation("[{MeetingId}] Transcript polling started (Graph onlineMeetings API)", meetingId);

        while (!ct.IsCancellationRequested)
        {
            try
            {
                // Step 1 — resolve organizer user ID from call info (once)
                if (organizerId is null)
                {
                    organizerId = await GetCallOrganizerIdAsync(callId, ct);
                    if (organizerId is not null)
                        _logger.LogInformation("[{MeetingId}] Organizer resolved: {OrgId}", meetingId, organizerId);
                    else
                        _logger.LogWarning("[{MeetingId}] Could not resolve organizer ID yet (will retry)", meetingId);
                }

                // Step 2 — resolve onlineMeeting ID via joinWebUrl filter (once)
                if (organizerId is not null && onlineMeetingId is null)
                {
                    onlineMeetingId = await GetOnlineMeetingIdAsync(organizerId, meeting.JoinUrl, ct);
                    if (onlineMeetingId is not null)
                        _logger.LogInformation("[{MeetingId}] OnlineMeeting resolved: {OMId}", meetingId, onlineMeetingId);
                    else
                        _logger.LogWarning("[{MeetingId}] Could not resolve onlineMeeting ID yet (will retry)", meetingId);
                }

                // Step 3 — fetch and push any new VTT cues
                if (organizerId is not null && onlineMeetingId is not null)
                    await FetchNewSegmentsAsync(organizerId, onlineMeetingId, meetingId, vttOffset, ct);
            }
            catch (OperationCanceledException) { break; }
            catch (Exception ex) when (!ct.IsCancellationRequested)
            {
                _logger.LogWarning(ex, "[{MeetingId}] Transcript poll error (will retry in 5s)", meetingId);
            }

            try { await Task.Delay(5_000, ct); } catch (OperationCanceledException) { break; }
        }

        _logger.LogInformation("[{MeetingId}] Transcript polling stopped", meetingId);
    }

    private async Task<string?> GetCallOrganizerIdAsync(string callId, CancellationToken ct)
    {
        // Try both the meeting tenant and the home tenant — the call object is readable
        // with whichever tenant token was used to create the call.
        var tenants = new[]
        {
            _config["MeetingTenantId"] ?? _config["MicrosoftAppTenantId"]!,
            _config["MicrosoftAppTenantId"]!
        }.Distinct().ToArray();

        foreach (var tenantId in tenants)
        {
            var token = await GetAccessTokenAsync(tenantId, ct);
            var req = new HttpRequestMessage(HttpMethod.Get,
                $"{GraphBase}/communications/calls/{callId}");
            req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var resp = await _http.SendAsync(req, ct);
            if (!resp.IsSuccessStatusCode)
            {
                _logger.LogWarning("GetCallOrganizerIdAsync: GET calls/{CallId} → {Status} (tenant {Tenant})",
                    callId, resp.StatusCode, tenantId[..8]);
                continue;
            }

            var body = await resp.Content.ReadAsStringAsync(ct);
            _logger.LogInformation("GetCallOrganizerIdAsync: call info (tenant {Tenant}): {Body}",
                tenantId[..8], body[..Math.Min(body.Length, 800)]);

            using var doc = JsonDocument.Parse(body);
            var root = doc.RootElement;

            // Primary: meetingInfo.organizer.user.id (returned by Graph on join)
            if (root.TryGetProperty("meetingInfo", out var meetingInfo) &&
                meetingInfo.TryGetProperty("organizer", out var organizer) &&
                organizer.TryGetProperty("user", out var orgUser) &&
                orgUser.TryGetProperty("id", out var orgUid) &&
                orgUid.GetString() is { Length: > 0 } orgId)
                return orgId;

            // Fallback: participants list → first real user (non-application)
            if (root.TryGetProperty("participants", out var participants) &&
                participants.ValueKind == JsonValueKind.Array)
            {
                foreach (var p in participants.EnumerateArray())
                {
                    if (!p.TryGetProperty("info", out var info)) continue;
                    if (!info.TryGetProperty("identity", out var identity)) continue;
                    if (!identity.TryGetProperty("user", out var user)) continue;
                    if (user.TryGetProperty("id", out var uid) && uid.GetString() is { } id)
                        return id;
                }
            }

            _logger.LogWarning("GetCallOrganizerIdAsync: no organizer found in response (tenant {Tenant})", tenantId[..8]);
        }

        return null;
    }

    private async Task<string?> GetOnlineMeetingIdAsync(string organizerId, string joinUrl, CancellationToken ct)
    {
        var tenantId = _config["MeetingTenantId"] ?? _config["MicrosoftAppTenantId"]!;
        var token = await GetAccessTokenAsync(tenantId, ct);

        var filter = Uri.EscapeDataString($"joinWebUrl eq '{joinUrl}'");
        var req = new HttpRequestMessage(HttpMethod.Get,
            $"{GraphBase}/users/{organizerId}/onlineMeetings?$filter={filter}&$select=id");
        req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

        var resp = await _http.SendAsync(req, ct);
        if (!resp.IsSuccessStatusCode)
        {
            var errBody = await resp.Content.ReadAsStringAsync(ct);
            _logger.LogWarning("GetOnlineMeetingIdAsync: filter failed {Status} — check OnlineMeetings.Read.All. Error: {Err}",
                resp.StatusCode, errBody[..Math.Min(errBody.Length, 400)]);
            return null;
        }

        var body = await resp.Content.ReadAsStringAsync(ct);
        using var doc = JsonDocument.Parse(body);
        if (doc.RootElement.TryGetProperty("value", out var arr) &&
            arr.ValueKind == JsonValueKind.Array &&
            arr.GetArrayLength() > 0 &&
            arr[0].TryGetProperty("id", out var mid))
            return mid.GetString();

        return null;
    }

    private async Task FetchNewSegmentsAsync(
        string organizerId, string onlineMeetingId, string meetingId,
        Dictionary<string, int> vttOffset, CancellationToken ct)
    {
        var tenantId = _config["MeetingTenantId"] ?? _config["MicrosoftAppTenantId"]!;
        var token = await GetAccessTokenAsync(tenantId, ct);

        // List all transcripts for this meeting
        var listReq = new HttpRequestMessage(HttpMethod.Get,
            $"{GraphBase}/users/{organizerId}/onlineMeetings/{onlineMeetingId}/transcripts");
        listReq.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

        var listResp = await _http.SendAsync(listReq, ct);
        if (!listResp.IsSuccessStatusCode)
        {
            var errBody = await listResp.Content.ReadAsStringAsync(ct);
            _logger.LogWarning("FetchNewSegmentsAsync: transcripts list {Status} — check OnlineMeetingTranscript.Read.All. Error: {Err}",
                listResp.StatusCode, errBody[..Math.Min(errBody.Length, 400)]);
            return;
        }

        var listBody = await listResp.Content.ReadAsStringAsync(ct);
        using var listDoc = JsonDocument.Parse(listBody);
        if (!listDoc.RootElement.TryGetProperty("value", out var transcripts) ||
            transcripts.ValueKind != JsonValueKind.Array)
            return;

        foreach (var t in transcripts.EnumerateArray())
        {
            if (!t.TryGetProperty("id", out var tidProp)) continue;
            var transcriptId = tidProp.GetString()!;

            // Download VTT content
            var vttReq = new HttpRequestMessage(HttpMethod.Get,
                $"{GraphBase}/users/{organizerId}/onlineMeetings/{onlineMeetingId}" +
                $"/transcripts/{transcriptId}/content?$format=text/vtt");
            vttReq.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var vttResp = await _http.SendAsync(vttReq, ct);
            if (!vttResp.IsSuccessStatusCode) continue;

            var vtt = await vttResp.Content.ReadAsStringAsync(ct);
            if (!vttOffset.TryGetValue(transcriptId, out var offset)) offset = 0;
            if (vtt.Length <= offset) continue;

            // Only parse the NEW portion (VTT is append-only)
            var newVtt = vtt[offset..];
            vttOffset[transcriptId] = vtt.Length;

            ParseAndPushVtt(newVtt, meetingId);
        }
    }

    // Parse Teams-style VTT fragment and push segments to the store.
    // Teams VTT format:
    //   WEBVTT
    //
    //   00:00:01.000 --> 00:00:04.000 align:start position:0%
    //   <v John Doe>Hello world</v>
    private void ParseAndPushVtt(string vtt, string meetingId)
    {
        var lines = vtt.Split('\n');
        for (int i = 0; i < lines.Length; i++)
        {
            var line = lines[i].TrimEnd('\r', ' ');

            // Timestamp line: "HH:MM:SS.mmm --> HH:MM:SS.mmm ..."
            if (!line.Contains(" --> ")) continue;

            var startTime = line.Split(' ')[0];
            var ts = ParseVttTime(startTime);

            // Collect payload lines until blank line
            string? speaker = null;
            var textParts = new List<string>();

            for (int j = i + 1; j < lines.Length; j++)
            {
                var payload = lines[j].TrimEnd('\r', ' ');
                if (string.IsNullOrEmpty(payload)) break;

                // <v Speaker Name>text</v>
                if (payload.StartsWith("<v ", StringComparison.Ordinal) && payload.Contains('>'))
                {
                    var end = payload.IndexOf('>');
                    speaker = payload[3..end].Trim();
                    payload = payload[(end + 1)..];
                    if (payload.EndsWith("</v>", StringComparison.Ordinal))
                        payload = payload[..^4];
                }

                if (!string.IsNullOrWhiteSpace(payload))
                    textParts.Add(payload.Trim());
            }

            var text = string.Join(" ", textParts).Trim();
            if (string.IsNullOrWhiteSpace(text)) continue;

            var segment = new TranscriptSegment(
                MeetingId:  meetingId,
                Text:       text,
                Language:   "en-US",
                Timestamp:  ts,
                Confidence: 1.0,
                SpeakerId:  speaker
            );
            _store.AddSegment(segment);
            _logger.LogInformation("[{MeetingId}] Transcript: [{Speaker}] {Text}",
                meetingId, speaker ?? "?", text);
        }
    }

    private static double ParseVttTime(string t)
    {
        try
        {
            var parts = t.Replace(',', '.').Split(':');
            var h   = int.Parse(parts[0]);
            var min = int.Parse(parts[1]);
            var sec = double.Parse(parts[2], System.Globalization.CultureInfo.InvariantCulture);
            return h * 3600 + min * 60 + sec;
        }
        catch { return DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() / 1000.0; }
    }
}
